name: CI

on:
    pull_request:
        branches:
            - master

jobs:

    security-checker:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master

            - name: install security-checker
              run: wget -O ./tools/security-checker.phar https://get.sensiolabs.org/security-checker.phar && ln -s security-checker.phar ./tools/security-checker && chmod +x ./tools/security-checker.phar

            - name: run security check
              run: ./tools/security-checker security:check

    composer-require-checker:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master

            - name: install composer-require-checker
              run: ./tools/phive.phar install --trust-gpg-keys D2CCAC42F6295E7D composer-require-checker

            - name: install composer packages
              run: ./tools/composer.phar install

            - name: run composer-require-checker
              run: ./tools/composer-require-checker

    composer-normalize:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master

            - name: run composer-normalize
              uses: docker://localheinz/composer-normalize-action:latest

    php-cs-fixer:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master

            - name: install php-cs-fixer
              run: ./tools/phive.phar install --trust-gpg-keys E82B2FB314E9906E php-cs-fixer

            - name: run php-cs-fixer
              run: ./tools/php-cs-fixer fix --config=.php_cs --dry-run --diff

    phan:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master

            - name: Installing php-ast
              run: sudo apt-get install php-ast

            - name: install composer packages
              run: ./tools/composer.phar install

            - name: install phan
              run: ./tools/phive.phar install --trust-gpg-keys AFA6EAAB339B841E phan

            - name: run phan
              run: ./tools/phan --config-file phan.php

    psalm:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master

            - name: install composer packages
              run: ./tools/composer.phar install

            - name: install psalm
              run: ./tools/phive.phar install --trust-gpg-keys 8A03EA3B385DBAA1 psalm

            - name: run psalm
              run: ./tools/psalm --config=psalm.xml

    build:
        runs-on: ubuntu-latest
        needs: [psalm, phan, php-cs-fixer, composer-normalize, composer-require-checker, security-checker]
        steps:
            - uses: actions/checkout@master

            - name: build docker image
              run: docker build --file Dockerfile --tag tomtomsen/project-euler:build-${GITHUB_SHA} .

            - name: run docker image
              run: docker run --rm tomtomsen/project-euler:build-${GITHUB_SHA} run 1
