name: CI

on:
    pull_request:
        branches:
            - master

jobs:
    security-checker:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master

            - name: install security-checker
              run: wget -O ./tools/security-checker.phar https://get.sensiolabs.org/security-checker.phar && ln -s security-checker.phar ./tools/security-checker && chmod +x ./tools/security-checker.phar

            - name: run security check
              run: ./tools/security-checker security:check

    php-cs-fixer:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master

            - name: install php-cs-fixer
              run: ./tools/phive.phar install --trust-gpg-keys BBAB5DF0A0D6672989CF1869E82B2FB314E9906E php-cs-fixer

            - name: run php-cs-fixer
              run: ./tools/php-cs-fixer fix --config=.php_cs --dry-run --diff

    phan:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master

            - name: install phan
              run: ./tools/phive.phar install --trust-gpg-keys DD0E869F43C6D0B10E2E2F19AFA6EAAB339B841E phan

            - name: run phan
              run: ./tools/phan --config-file phan.php

    psalm:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master

            - name: install psalm
              run: ./tools/phive.phar install --trust-gpg-keys 5EAE7E975CE1510C4F54D4B08A03EA3B385DBAA1 psalm

            - name: run psalm
              run: ./tools/psalm --config=psalm.xml
